export default fakeApi = [
  {
    quantity: "500",
    description: "Ingreso con descripción",
    income: true,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "400",
    description: "Gasto con descripción",
    income: false,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "500",
    description: "Ingreso con descripción",
    income: true,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "400",
    description: "Gasto con descripción",
    income: false,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "500",
    description: "Ingreso con descripción",
    income: true,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "400",
    description: "Gasto con descripción",
    income: false,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "500",
    description: "Ingreso con descripción",
    income: true,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "400",
    description: "Gasto con descripción",
    income: false,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "500",
    description: "Ingreso con descripción",
    income: true,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "400",
    description: "Gasto con descripción",
    income: false,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "500",
    description: "Ingreso con descripción",
    income: true,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "400",
    description: "Gasto con descripción",
    income: false,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "500",
    description: "Ingreso con descripción",
    income: true,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "400",
    description: "Gasto con descripción",
    income: false,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "500",
    description: "Ingreso con descripción",
    income: true,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "400",
    description: "Gasto con descripción",
    income: false,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "500",
    description: "Ingreso con descripción",
    income: true,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  },
  {
    quantity: "400",
    description: "Gasto con descripción",
    income: false,
    hour: "3:43 pm",
    date: "Mar 25 2015",
  }
];
