export default fakeApi = [
  {
    description: "Ingreso con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "500",
    income: true,
  },
  {
    description: "Gasto con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "400",
    income: false,
  },
  {
    description: "Ingreso con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "500",
    income: true,
  },
  {
    description: "Gasto con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "400",
    income: false,
  },
  {
    description: "Ingreso con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "500",
    income: true,
  },
  {
    description: "Gasto con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "400",
    income: false,
  },
  {
    description: "Ingreso con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "500",
    income: true,
  },
  {
    description: "Gasto con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "400",
    income: false,
  },
  {
    description: "Ingreso con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "500",
    income: true,
  },
  {
    description: "Gasto con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "400",
    income: false,
  },
  {
    description: "Ingreso con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "500",
    income: true,
  },
  {
    description: "Gasto con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "400",
    income: false,
  },
  {
    description: "Ingreso con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "500",
    income: true,
  },
  {
    description: "Gasto con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "400",
    income: false,
  },
  {
    description: "Ingreso con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "500",
    income: true,
  },
  {
    description: "Gasto con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "400",
    income: false,
  },
  {
    description: "Ingreso con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "500",
    income: true,
  },
  {
    description: "Gasto con descripción",
    date: "Mar 25 2015",
    hour: "3:43 pm",
    quantity: "400",
    income: false,
  }
];
