# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'oinkiiApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for oinkiiApp
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'

  target 'oinkiiApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'oinkiiAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
